pipeline {
    agent {
      docker{
       image 'python:2.7.16-slim'
       args '--user root'
            }
          }


    stages {
        stage('build') {
          when{
                changeset "**/vote/**"
               }
            steps {
                echo 'this is vote build job'
                dir('vote'){
                sh 'pip install -i requirements.txt'
                }
            }
       }
       stage('test') {
       when {
                changeset "**/vote/**"
            }
           steps {
               echo 'this is vote test job'
               dir('vote'){
               sh 'nosetests -v'
               }
           }
           }

    }
    post{
    always{
    echo 'pipeline for vote is complete'
          }
    failure{
    slackSend (channel: "instavote-cd" , message:"Build failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
          }
    success{
    slackSend (channel: "instavote-cd" , message:"Build succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    }
}
