pipeline {
    agent none


    stages {
        stage('build') {
        agent {
          docker{
           image 'python:2.7.16-slim'
           args '--user root'
                }
              }
          when{
                changeset "**/vote/**"
               }
            steps {
                echo 'this is vote build job'
                dir('vote'){
                sh 'pip install -r requirements.txt'
                }
            }
       }
       stage('test') {
       agent {
         docker{
          image 'python:2.7.16-slim'
          args '--user root'
               }
             }
       when {
                changeset "**/vote/**"
            }
           steps {
               echo 'this is vote test job'
               dir('vote'){
               sh 'nosetests  -v'
               }
           }
           }
           stage('docker-package'){
             agent any
              when {

                       changeset "**/vote/**"
                   }
                   steps{
                        echo 'Packging vote app with docker'
                     script{
                     docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                     def voteImage = docker.build("saumya043/vote:v${env.BUILD_ID}", "./vote")
                     voteImage.push()

                  }
                }
             }
           }

    }
    post{
    always{
    echo 'pipeline for vote is complete'
          }
    failure{
    slackSend (channel: "instavote-cd" , message:"Build failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
          }
    success{
    slackSend (channel: "instavote-cd" , message:"Build succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    }
}
