version: "3.8"

volumes: 
  db-data:

networks:
  instavote:
     driver: bridge

services:
  vote:
    image: saumya043/vote:master
    build: ./vote
    ports:
      - 5000:80
    depends_on:
      - redis 
    networks:
      - instavote

  result:
    image: saumya043/result:master
    build: ./result
    ports: 
      - 5001:4000
    depends_on:
            - db
    networks: 
      - instavote  

  redis: 
   image: redis:alpine
   networks: 
     - instavote

  db:
    image: postgres:9.4
    networks: 
      - instavote
    volumes: 
      - "db-data:/var/lib/postgresql/data" 


  worker:
    image: saumya043/worker:master
    build: ./worker
    depends_on: 
       - db
       - redis  
    networks: 
      - instavote


