pipeline {
    agent any
    tools {
     maven 'maven 3.6.1'
    }

    stages {
        stage('build') {
            steps {
                echo 'this is worker build job'
                dir('worker'){
                sh 'mvn compile'
                }
            }
       }
       stage('test') {
           steps {
               echo 'this is worker test job'
               dir('worker'){
               sh 'mvn clean test'
               }
           }
           }

       }
       stage('package'){
           steps{
               echo 'this is package job'
               dir('worker'){
               sh 'mvn package -DskipTests'
               }
           }
           }
       }
    }
    post{
    always{
    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
    echo 'pipeline for worker is complete'
          }
    }
}
